version: '3.1'

services:
  app:
    image: '6ea6eca9019c'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=aks
      - DB_URL=jdbc:postgresql://db:5432/YTSpringCourse
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aks
